---

- name: "Configure {{ hadoop_datanode_core_site_file }}"
  template:
    src: core-site.xml.j2
    dest: "{{ hadoop_datanode_core_site_file }}"
    validate: "xmllint %s"
  when: hadoop_datanode_core_site_file

- name: "Configure {{ hadoop_datanode_hdfs_site_file }}"
  template:
    src: hdfs-site.xml.j2
    dest: "{{ hadoop_datanode_hdfs_site_file }}"
    validate: "xmllint %s"
  when: hadoop_datanode_hdfs_site_file

- name: "Configure {{ hadoop_datanode_mapred_site_file }}"
  template:
    src: mapred-site.xml.j2
    dest: "{{ hadoop_datanode_mapred_site_file }}"
    validate: "xmllint %s"
  when: hadoop_datanode_mapred_site_file

- name: "Configure {{ hadoop_namenode_yarn_site_file }}"
  template:
    src: yarn-site.xml.j2
    dest: "{{ hadoop_namenode_yarn_site_file }}"
    validate: "xmllint %s"
  when: hadoop_namenode_yarn_site_file
