---

- name: Install hadoop
  pkgng:
    name: hadoop2
    state: present

- name: fix status command in namenode
  patch:
    src: patch-namenode
    dest: /usr/local/etc/rc.d/namenode

- name: fix status command in datanode
  patch:
    src: patch-datanode
    dest: /usr/local/etc/rc.d/datanode
