---
# tasks file for ansible-role-hadoop

- include_vars: "{{ ansible_os_family }}.yml"

- include: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: Create log directory
  file:
    path: "{{ hadoop_datanode_log_dir }}"
    mode: 0775
    owner: "{{ hadoop_datanode_user }}"
    group: "{{ hadoop_datanode_group }}"
    state: directory
  notify:
    - Restart datanode
    - Restart nodemanager

- name: Create db directory
  file:
    path: "{{ hadoop_datanode_db_dir }}"
    mode: 0775
    owner: "{{ hadoop_datanode_user }}"
    group: "{{ hadoop_datanode_group }}"
    state: directory
  notify:
    - Restart datanode
    - Restart nodemanager

- name: Create dfs.datanode.name.dir
  file:
    path: "{{ hadoop_datanode_dfs_datanode_data_dir }}"
    mode: 0700
    owner: "{{ hadoop_datanode_user }}"
    group: "{{ hadoop_datanode_group }}"
    state: directory
  notify:
    - Restart datanode
    - Restart nodemanager

- include: configure-xml.yml

- name: Create slaves file
  template:
    src: slaves.j2
    dest: "{{ hadoop_datanode_conf_dir }}/slaves"
  notify:
    - Restart datanode
    - Restart nodemanager

- name: Start hadoop datanode
  service:
    name: "{{ hadoop_datanode_service }}"
    enabled: true
    state: started

- name: Start hadoop nodemanager
  service:
    name: "{{ hadoop_datanode_nodemanager_service }}"
    enabled: true
    state: started
